### ISSUE TITLE
README setup guide for Windows is outdated

### ISSUE THREAD

**Issue by zpervan** [Seviel/Rinvid#70]
Consider revisiting the setup guide for Windows. Installing the MinGW and SFML dependencies could be done via `pacman`.
Steps 3, 4, 5, 6, 7, and 8 could be removed and use the following command in the MSYS shell:
```shell 
pacman -S --needed base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-sfml
```

Plus, seems that some links are broken in the guide.

**Comment by Seviel** [comment]
Yeah, this definitely is more normal way of setting up. Do you plan to make the changes to the setup guide or are you just bringing attention that it needs fixing?

**Comment by zpervan** [comment]
I created the pull request so you can take a look

**Comment by Seviel** [comment]
Thanks for the contribution, much appreciated! If you're interesting to contributing more to the project, you can add me on Discord: Seviel#4818
We can talk there about what you would like to do and what needs to be done.
